# Generated by Django 5.0.4 on 2024-04-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "documento",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Numero de documento"
                    ),
                ),
                (
                    "apellidos",
                    models.CharField(
                        max_length=30, verbose_name="Apellidos de la persona"
                    ),
                ),
                (
                    "nombres",
                    models.CharField(
                        max_length=30, verbose_name="Nombres de la persona"
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(verbose_name="Fecha de nacimiento"),
                ),
                (
                    "nacionalidad",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Nacionalidad",
                    ),
                ),
                (
                    "correo",
                    models.EmailField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="Correo electronico",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "ultima_actualizacion",
                    models.DateField(verbose_name="Ultima actualizacion"),
                ),
            ],
        ),
    ]
